
import { ScheduleItem, LocationTodo, TravelRecommendation } from '@/types';

export const todaySchedule: ScheduleItem[] = [
  {
    id: '0',
    title: '준비',
    startTime: '08:00',
    endTime: '09:00',
    category: 'other',
    icon: '🏠',
    color: 'bg-gray-400',
    isAutoGenerated: true
  },
  {
    id: '0-1',
    title: '이동 (집 → 잠실역)',
    startTime: '09:00',
    endTime: '09:50',
    category: 'travel',
    icon: '🚇',
    color: 'bg-indigo-400',
    distance: '도보 10분, 지하철 40분',
    isAutoGenerated: true,
    travelTime: 50
  },
  {
    id: '1',
    title: '우아한테크코스 출근',
    startTime: '09:50',
    endTime: '10:00',
    location: '잠실역',
    category: 'course',
    icon: '🚶',
    color: 'bg-blue-500',
    distance: '도보 10분, 500m',
    isAutoGenerated: true
  },
  {
    id: '2',
    title: '[강의] 레벨3 오리엔테이션',
    startTime: '10:00',
    endTime: '10:30',
    location: '우아한테크코스',
    category: 'course',
    icon: '🎓',
    color: 'bg-orange-500',
    isAutoGenerated: true
  },
  {
    id: '2-1',
    title: '이동 (우테코 → 루터회관)',
    startTime: '11:55',
    endTime: '12:00',
    category: 'travel',
    icon: '🚶',
    color: 'bg-indigo-400',
    distance: '도보 5분',
    isAutoGenerated: true,
    travelTime: 5
  },
  {
    id: '3',
    title: '점심',
    startTime: '12:00',
    endTime: '13:00',
    location: '루터회관',
    category: 'meal',
    icon: '🍽️',
    color: 'bg-yellow-500'
  },
  {
    id: '4-1',
    title: '이동 (루터회관 → 다이소)',
    startTime: '15:45',
    endTime: '16:00',
    category: 'travel',
    icon: '🚇',
    color: 'bg-indigo-400',
    distance: '지하철 15분',
    isAutoGenerated: true,
    travelTime: 15
  },
  {
    id: '4',
    title: '다이소',
    startTime: '16:00',
    endTime: '16:30',
    location: '다이소',
    category: 'shopping',
    icon: '🛒',
    color: 'bg-green-500'
  },
  {
    id: '5-1',
    title: '이동 (다이소 → 헬스장)',
    startTime: '17:30',
    endTime: '18:00',
    category: 'travel',
    icon: '🚇',
    color: 'bg-indigo-400',
    distance: '지하철 + 도보 30분',
    isAutoGenerated: true,
    travelTime: 30
  },
  {
    id: '5',
    title: '헬스장',
    startTime: '18:00',
    endTime: '19:30',
    location: '헬스장',
    category: 'fitness',
    icon: '💪',
    color: 'bg-purple-500'
  }
];

export const locationTodos: LocationTodo[] = [
  {
    id: '1',
    location: '다이소',
    task: '칫솔 사기',
    isCompleted: false,
    category: 'shopping'
  },
  {
    id: '2',
    location: '우테코',
    task: '페어룸 예약하기',
    isCompleted: false,
    category: 'course'
  }
];

export const travelRecommendation: TravelRecommendation = {
  destination: '우아한테크코스 캠퍼스',
  departureTime: '08:23',
  arrivalTime: '17:42',
  travelDuration: '35분',
  distance: '12.3km',
  route: '5분 → 20분 → 7분 → 3분'
};
